config/routes.rb
Rails.application.routes.draw do
  resources :starter_packs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/starter_pack.rb
class StarterPack < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController  
    def index
    end
end  

app/controllers/starter_packs_controller.rb
class StarterPacksController < ApplicationController
  before_action :set_starter_pack, only: %i[ show edit update destroy ]

  # GET /starter_packs or /starter_packs.json
  def index
    @starter_packs = StarterPack.all
  end

  # GET /starter_packs/1 or /starter_packs/1.json
  def show
  end

  # GET /starter_packs/new
  def new
    @starter_pack = StarterPack.new
  end

  # GET /starter_packs/1/edit
  def edit
  end

  # POST /starter_packs or /starter_packs.json
  def create
    @starter_pack = StarterPack.new(starter_pack_params)

    respond_to do |format|
      if @starter_pack.save
        format.html { redirect_to starter_pack_url(@starter_pack), notice: "Starter pack was successfully created." }
        format.json { render :show, status: :created, location: @starter_pack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @starter_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /starter_packs/1 or /starter_packs/1.json
  def update
    respond_to do |format|
      if @starter_pack.update(starter_pack_params)
        format.html { redirect_to starter_pack_url(@starter_pack), notice: "Starter pack was successfully updated." }
        format.json { render :show, status: :ok, location: @starter_pack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @starter_pack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /starter_packs/1 or /starter_packs/1.json
  def destroy
    @starter_pack.destroy!

    respond_to do |format|
      format.html { redirect_to starter_packs_url, notice: "Starter pack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_starter_pack
      @starter_pack = StarterPack.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def starter_pack_params
      params.require(:starter_pack).permit(:name, :icon, :title, :image_one, :image_two, :image_three, :image_four, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/starter_packs_helper.rb
module StarterPacksHelper
end

app/views/home/index.html.erb
<div class="container">

    <a class="icon" href="/starter_packs"><img src="https://cdn.discordapp.com/attachments/1210360796194799677/1210360952474574898/starterpackexe.png?ex=65ea477a&is=65d7d27a&hm=f7a013ab0d6664329a767d519d4849f530b6d980cc8239d723b109e50eb8e6f5&" alt="" width="100px"></a>
    <a class="icon2" href="./#window2"><img src="https://cdn.discordapp.com/attachments/1210360796194799677/1210361119835955361/adminexe.png?ex=65ea47a2&is=65d7d2a2&hm=31b5344bccbad08fb23d5d190549b86a22e6e203b406b5f6b1d6d089941788dd&" alt="" width="100px"></a>

    <div id="window2" class="modal2">
        <div class="modal2_content">
                <img src="https://imgbox.com/T8MHSahP" alt="" width="400">
                
                <a href="#" class="modal2_close">&times;</a>
                
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>starter packs!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "pack", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="shortcut icon" href="/PATH_TO_STATIC_FAVICON/favicon.ico" type="image/x-icon"> 
    <link rel="icon" href="/PATH_TO_ANIMATED_FAVICON/favicon.ico" type="image/x-icon">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/starter_packs/_form.html.erb
<%= form_with(model: starter_pack) do |form| %>
  <% if starter_pack.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(starter_pack.errors.count, "error") %> prohibited this starter_pack from being saved:</h2>

      <ul>
        <% starter_pack.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section class="formulaire">
    <div class="col-1">
      <div class="case">
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div class="case">
        <%= form.label :title, style: "display: block" %>
        <%= form.text_area :title %>
      </div>

      <div class="case">
        <%= form.label :icon, style: "display: block" %>
        <%= form.text_area :icon %>
      </div>

      <div class="case">
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description %>
      </div>

    </div>

    <div class="col-2">
      <div class="case">
        <%= form.label :image_one, style: "display: block" %>
        <%= form.text_area :image_one %>
      </div>

      <div class="case">
        <%= form.label :image_two, style: "display: block" %>
        <%= form.text_area :image_two %>
      </div>

      <div class="case">
        <%= form.label :image_three, style: "display: block" %>
        <%= form.text_area :image_three %>
      </div>

      <div class="case">
        <%= form.label :image_four, style: "display: block" %>
        <%= form.text_area :image_four %>
      </div>

      <div class="create">
        <%= form.submit %>
      </div>
    </div>
    
  </section>



<% end %>

app/views/starter_packs/_starter_pack.html.erb
<div class="containerPack">
  <div id="<%= dom_id starter_pack %>" class="pack">
    <div class="flexpack">
      <div class="packTitle">
        <h1>
          <%= starter_pack.name %>
        </h1>
          <ul class="link">
            <li>➜ <b>starterpack</b> request:(guest) <%= link_to "/return", starter_packs_path %></li>
            <li>➜ <b>starterpack</b> request:(admin) <%= link_to "/modify", edit_starter_pack_path(@starter_pack) %></li>
            <li><%= button_to "Destroy this starter pack", @starter_pack, method: :delete, class:'button-delete' %></li>
            </ul>
      </div>

      <div class="packImages">
          <div class="iconTitleBox">
            <%= image_tag starter_pack.icon %>
            <h2>
            <%= starter_pack.title %>
            </h2>
          </div>

          <div class="listImages">
              <a href="<%= starter_pack.image_one %>" target="_blank"><%= image_tag starter_pack.image_one %></a>

              <a href="<%= starter_pack.image_two %>" target="_blank"><%= image_tag starter_pack.image_two %></a>

              <a href="<%= starter_pack.image_three %>" target="_blank"><%= image_tag starter_pack.image_three %></a>

              <a href="<%= starter_pack.image_four %>" target="_blank"><%= image_tag starter_pack.image_four %></a>
          </div>
      </div>
    </div>

    <div class="packDescription">
      <p>
        <%= starter_pack.description %>
      </p>
    </div>

  </div>
</div>

app/views/starter_packs/edit.html.erb
<div class="container">
  <div class="blocnote">
    <div class="textform">
      <h1>Update starterpack</h1>
      <p>Modifie les informations d'un starterpack !</p>
      <ul class="link">
        <li>➜ <b>starterpack</b> request:(admin) <a href="/#">/return index</a></li>
        <li>➜ <b>starterpack</b> request:(admin) <%= link_to "/show this starter pack", @starter_pack %></li>
        <li>➜ <b>starterpack</b> request:(admin) <%= link_to "/return starterpacks", starter_packs_path %></li>
      </ul>
    </div>

    <%= render "form", starter_pack: @starter_pack %>
  </div>
</div>

app/views/starter_packs/index.html.erb
<div class="container">
  <div class="mainContainer">
  <div class="nav">
    <h1>starter_packs.exe</h1>
    <a href="./#" class="backButton"><img src="https://cdn.discordapp.com/attachments/1210360796194799677/1210587215109816380/buttonclose.png?ex=65eb1a33&is=65d8a533&hm=81c87c765042a7a59cdec5b1b39cb015164fd812117cace799cd15089e7d2ae4&%20/%3E%3C/a%3E%20%20%3C/div%3E%20%20%20%20%3Cdiv%20class=" /></a>
  </div>

  
  <div class="introductionContainer">
    <img src="https://images2.imgbox.com/e2/04/OIsU7NUn_o.png" /> 
    <h2>quel starterpack veux-tu ?<h2>
  </div>

  <div id="starter_packs" class="insideContainer">
    <ul>
      <% @starter_packs.each do |starter_pack| %>
      <li>
        <%= image_tag starter_pack.icon %><br>
        <%= link_to starter_pack.name, starter_pack %>
      </li>
      <% end %>
    </ul>
  </div>

<!-- pour n'autorisée qu'un admin : if user.id = (le user.id dans bdd) 
  puts link_to etcetc -->
  <p class="link">➜ <b>starterpack</b> request:(admin) <%= link_to "créer un nouveau pack", new_starter_pack_path %></p>

  <p class="information"><%= notice %></p>
</div>
</div>

app/views/starter_packs/new.html.erb
<div class="container">
  <div class="blocnote">
    <div class="textform">
      <h1>New starter pack</h1>
      <p> Remplis ce formulaire avec du texte et des liens vers les images de ton choix !</p>
      <ul class="link">
        <li>➜ <b>starterpack</b> request:(admin) <a href="/#">/return index</a></li>
        <li>➜ <b>starterpack</b> request:(admin) <%= link_to "/return starter packs", starter_packs_path %></li>
      </ul>
    </div>

    <%= render "form", starter_pack: @starter_pack %>
  </div>
</div>

app/views/starter_packs/show.html.erb
<%= render @starter_pack %>

<div>
  <%= link_to "Edit this starter pack", edit_starter_pack_path(@starter_pack) %> |
  <%= link_to "Back to starter packs", starter_packs_path %>

  <%= button_to "Destroy this starter pack", @starter_pack, method: :delete %>
</div>
<p style="color: green, position: absolute"><%= notice %></p>